services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: biko_front
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env.local